/*
 Caso querie apagar todas as tabelas para testar novamente
 */

DROP TABLE "flyway_schema_history";
DROP TABLE ALLERGY;
DROP TABLE CAUTIONLIST;
DROP TABLE CONSULT;
DROP TABLE EXAM;
DROP TABLE MEDICALSPECIALIZATION;
DROP TABLE SPECIALIZATION;
DROP TABLE PATIENT;
DROP TABLE ADDRESS;
DROP TABLE DOCTOR;
DROP TABLE PERSON;
