CREATE OR REPLACE VIEW V_STATISTICS AS
SELECT 'PATIENT' TYPE, COUNT(1) VALUE, MAX(PE.DTACREATED) LASTCREATED
FROM PATIENT PA
    INNER JOIN PERSON PE
ON PE.IDPERSON = PA.IDPERSON
UNION ALL

SELECT 'DOCTOR' TYPE, COUNT(1) VALUE, MAX(PE.DTACREATED) LASTCREATED
FROM DOCTOR PA
    INNER JOIN PERSON PE
ON PE.IDPERSON = PA.IDPERSON
UNION ALL

SELECT 'CONSULT' TYPE, COUNT(1) VALUE, MAX(CT.DTACREATED) LASTCREATED
FROM CONSULT CT
UNION ALL

SELECT 'EXAM' TYPE, COUNT(1) VALUE, MAX(EX.DTACREATED) LASTCREATED
FROM EXAM EX;
